jobs:
  - job: create_ADE
    variables:
      environmentName: 'WebApp'
    steps:
    - task: AzureCLI@2
      displayName: Deploy ADE Environment
      inputs:
        azureSubscription: AzureDevExtServiceConnection
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az devcenter dev environment create --dev-center-name dc-poc-dev-eus --project-name webappdev --catalog-name simple_devcenter --environment-definition-name ${{ variables.environmentName }}--environment-type CICD --name adesamplecicd --parameters Environments/${{ variables.environmentName }}/ade.parameters.json '
